apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-charts-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/matanweisz/helm-charts.git
        revision: main
        directories:
          - path: charts/*/values
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://matanweisz.github.io/helm-charts
        chart: '{{path.split("/")[1]}}'
        targetRevision: PLACEHOLDER_VERSION
        helm:
          valueFiles:
            - values/{{path.basename}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
