apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistory }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secret.name }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.deployment.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.deployment.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: BG_COLOR
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Values.deployment.configmap }}
                  key: {{ .Values.deployment.configmapKey }}
