deployment:
  name: "weather-app"
  replicas: 2
  image: "matanweisz/weather_app:latest"
  containerPort: 5000
  configmap: "blue"
  configmapKey: "BG_COLOR"

service:
  name: "weather-app-service"
  port: 80
  targetPort: 5000

secret:
  name: "docker-credential-secret"
  namespace: "default"

first:
  name: "blue"
  color: "blue"

second:
  name: "green"
  color: "green"
