# Weather App
deployment:
  name: "weather-app"
  replicas: 2
  revisionHistory: 0
  image: "matanweisz/weather_app:0.1.34"
  containerPort: 5000
  configmap: "bg-color"
  configmapKey: "BG_COLOR"
service:
  name: "weather-app-service"
  port: 80
  targetPort: 5000
secret:
  name: "docker-credential-secret"
  namespace: "apps"
# Configmap
configmap:
  name: "bg-color"
  color: "blue"
# Nginx Ingress
ingress:
  name: "weather-app-ingress"
  className: "nginx"
  host: "webapp.weather.local"
  portNumber: 80
