name: Auto Merge Chart Changes

on:
  push:
    branches:
      - main

jobs:
  detect-and-merge:
    name: Detect chart changes and merge to chart-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

            - name: Check for chart changes
        id: chart-changed
        run: |
          CHANGED_FILES=$(git diff --name-only origin/chart-release...HEAD || true)
          echo "$CHANGED_FILES" > changed_files.txt
          
          if grep -q '^charts/' changed_files.txt; then
            echo "Charts were changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No charts changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge main ➝ chart-release
        if: steps.chart-changed.outputs.changed == 'true'
        run: |
          git fetch origin chart-release
          git checkout -b temp-merge origin/chart-release
          git merge origin/main --no-edit
          git push origin HEAD:chart-release

