name: Release Charts

on:
  push:
    branches:
      - chart-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate Versions for Modified Charts
        id: version
        run: |
          DATE=$(date +'%d-%m-%Y')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION="$DATE-$COMMIT_HASH"
          echo "Using version: $VERSION"

          CHANGED=false
          for CHART in charts/*; do
            if git diff --name-only HEAD^ HEAD | grep "$CHART/" > /dev/null; then
              echo "Updating chart in $CHART"
              sed -i "s/^version:.*/version: \"$VERSION\"/" "$CHART/Chart.yaml"
              sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" "$CHART/Chart.yaml"
              CHANGED=true
            fi
          done

          if $CHANGED; then
            git add charts/*/Chart.yaml
            git commit -m "Auto-bump version to $VERSION"
            git push
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

