name: Helm Chart Release

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Pull Changes
        run: |
          git pull origin main

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Charts
        run: |
          mkdir -p release-packages
          helm package charts/weather-app -d release-packages/

      - name: Upload Charts to GitHub Release
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .cr.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Chart Packages to gh-pages
        run: |
          cp release-packages/* gh-pages/ || echo "No packages to copy"

      - name: Push Changes to gh-pages
        run: |
          cd gh-pages
          
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
          git add .
          git commit -m "Update Helm chart packages and index" || echo "No changes to commit"
          git push
